title = 'maisa moreira - blog'
baseURL = 'https://maisamrr.github.io/maisices'
languageCode = 'en-us'
theme = 'hugo-blog-awesome'

# Enable emojis globally
enableEmoji = true

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'hrdark'
    tabWidth = 4

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "maísa moreira"
  defaultColor = "dark" # set default color mode: dark or light or auto
  description = "my personal blog"
  mainSections = ['posts']

[params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "maísa moreira"
  name = "maísa moreira"
  description = "🌱 Estudante de Ciência da Computação em busca de compartilhar conhecimentos 💻 Aqui guardo conteúdos aleatórios relacionados à tecnologia"

[[params.socialIcons]] 
    name = "github" 
    url = "https://github.com/maisamrr" 
    
[[params.socialIcons]] 
    name = "twitter" 
    url = "https://twitter.com/maisamrr" 

[privacy]
    [privacy.disqus]
        disable = true