baseURL = 'https://maisamrr.github.io/maisices/'
languageCode = 'en-us'
title = 'maisices'
theme = 'hugo-ficurinia'

[params]
    author = 'maísa'
    description = "maisices - maísa's personal page"
    posts = "posts"

    logo = "/logo.svg"
    favicon = "/favicon.png" 
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png" 
    svgicon = "/logo.svg"
    icon512 = "/icon512.png"

    fontFamily = "JetBrains Mono"  
    titleFontFamily = "JetBrains Mono"
    monospaceFontFamily = "JetBrains Mono"

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "github"
        url = "https://github.com/maisamrr"
        weight = 10
    [[menu.icons]]
        identifier = "instagram"
        name = "instagram"
        url = "https://instagram.com/maisamoreira"
        weight = 10
    [[menu.icons]]
        identifier = "linkedin"
        name = "linkedin"
        url = "https://linkedin.com/maisammoreira"
        weight = 10
