baseUrl: https://maisamrr.github.io/maisices
languageCode: en-us
theme: hello-friend
copyright: ''
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: post
  # "dark" or "light"
  defaultTheme: light
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 2

languages:
  en:
    title: Maísa Moreira
    subtitle: 
    keywords: ''
    menuMore: Mais
    writtenBy: Por
    readMore: Leia mais
    readOtherPosts: Leia outros posts
    newerPosts: Posts mais recentes
    olderPosts: Posts mais antigos
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    
    params:
      logo:
        logoText: maísa moreira
        logoHomeLink: /maisices
    #   or
    #
    #   path: /img/your-example-logo.svg
    #   alt: Your example logo alt text
    
    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: links
        name: Links
        url: /links_uteis
    module:
      imports:
      - disable: false
        ignoreConfig: false
        ignoreImports: false
        path: github.com/panr/hugo-theme-hello-friend