baseURL = 'https://maisamrr.github.io/'
languageCode = 'en-us'
title = 'maisices'
theme = 'hugo-ficurinia'

[params]
    author = "Maísa Moreira"
    description = "Maísa's personal page" 

    posts = "posts" 
    showPostsLink = true  
    extraContentDirs = [] 
    showcaseDir = "showcase"  

    showSinglePageAsHome = false
    homeSinglePage = "/home"

    # It's best to put these icons in the "static" folder of your site
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico" 
    appletouch = "/apple-touch-icon.png"  
    svgicon = "/logo.svg"
    icon512 = "/icon512.png" 

    logoRightOfTitle = false 

    showTags = true  
    showRss = true  

    imageInArticlePreview = false 
    fitImageInArticlePreview = false 
    articleSummary = true  
    
    fontFamily = "JetBrains Mono"  # changes the font, default "JetBrains Mono"
    titleFontFamily = "JetBrains Mono"  # font used for titles and headings
    monospaceFontFamily = "JetBrains Mono"  # changes the monospace font for code, default "JetBrains Mono"

    titleFontSizeMultiplier = 1.0
    mainFontSizeMultiplier = 1.0
    monoFontSizeMultiplier = 1.0

    contentWidth = "1000px"  

    menuStyle = "standard"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"

    enableSearch = true  
    searchbarEverywhere = true  
    searchMenuLink = false  
    mobileHamburgerNav = false  

    enableFeatured = false  

    underlineTitleLinks = false  # show an underline also for links that are titles

[menu]
    # these links will be added to the main navigation menu, sorted by weight
    # other elements in this menu are added automatically from the "pages" folder
    # the folder it will look into can be customized with the pages variable
    # in params above
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.icons]]
        identifier = "gitlab"
        name = "GitLab"
        url = "https://gitlab.com/gabmus"
        weight = 10
    [[menu.icons]]
        identifier = "gnome"
        name = "GNOME GitLab"
        url = "https://gitlab.gnome.org/gabmus"
        weight = 20

[outputs]
    home = ["HTML", "JSON"]
